# Phase de build
FROM klakegg/hugo:0.92.2 as builder

# Copier le contenu du site Hugo dans le conteneur
COPY . /src

# Se déplacer dans le répertoire du site Hugo
WORKDIR /src

# Exécutez la commande Hugo pour générer le site statique
RUN hugo --minify || (echo "Hugo build failed" && exit 1)


# Phase de run
FROM nginx:latest as production

# Copier le site statique généré dans le conteneur NGINX
COPY --from=builder /src/public /usr/share/nginx/html

# Exposer le port 80
EXPOSE 80

# Commande pour démarrer NGINX
CMD ["nginx", "-g", "daemon off;"]
